const CONSTANTS = {
  ADD_PIZZA: 'ADD_PIZZA',
  REMOVE_PIZZA: 'REMOVE_PIZZA',
  ASYNC_ACTION: 'ASYNC_ACTION',
  RECEIVE_PIZZAS: 'RECEIVE_PIZZAS',
  TOGGLE_TOPPING: 'TOGGLE_TOPPING',
};

export default CONSTANTS;
